apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rag12c-sep16-2-app
  namespace: rhtap
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/rag12c-sep16-2/overlays/development
    repoURL: https://github.com/redhat-appstudio-mjf/rag12c-sep16-2-gitops.git
    targetRevision: main
  destination:
    namespace: rag12c-sep16-2
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: rhtap
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
