kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: imagestream-job-rolebinding-test
  namespace: redhat-ods-applications
subjects:
  - kind: ServiceAccount
    name: rag12c-sep16-2-dsp-job
    namespace: rag12c-sep16-2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: imagestream-job-role-test
