apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rag12c-sep16-2
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/maysunfaisal/rag12c-sep16-2:955274ec06d562a9078f50af412b618ecefb6aa1@sha256:80cb990069e3e0e5053fcd51666ff0145eec9c5e79651792235f358a0900cce4 # use pre-built to bootstrap 
          name: app-inference
